### ISSUE TITLE
Ajouter la possibilité d'éditer une partition

### ISSUE THREAD

**Issue by ascpial** [Philou-py/toccatech-next#1]
J'ai récemment uploadé une partition sur le site en me trompant dans le nom.
Apparemment, il n'y a pas de bouton pour éditer une partition, j'ouvre donc cette issue afin de proposer cette fonctionnalité/

**Comment by Philou-py** [comment]
Cher utilisateur de Toccatech,

Merci pour cette suggestion ! Avec la version du projet 2.0.0 récemment publiée, le site a été complètement reprogrammé en utilisant React et le framework Next.js ! De nouvelles fonctionnalité ont été ajoutées, et donc notamment la possibilité de modifier et supprimer les partitions de la partothèque.
Dû au changement de backend, il faudra exceptionnellement, pour cette mise à jour, recréer votre compte. Si vous souhaitez récupérer vos données, vous pouvez bien entendu m'envoyer un mail à l'adresse contact@toccatech.com !

**Comment by ascpial** [comment]
Merci pour la réponse, je vais jeter un coup d'oeil au nouveau site !
